### ISSUE TITLE
CORS issue on XAMPP

### ISSUE THREAD

**Issue by ThistleApps** [awes-io/demo#1]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior
Getting errors at login page.  Is CORS required?

## Current Behavior
I followed the manual installation for using Composer Install on XAMPP.  The login view doesnt show the login fields and the styling looks invalid.  Looking at the browser errors we can see the following:

Failed to load resource: the server responded with a status of 404 ()
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/theme-switcher/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/theme-switcher/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/virtual-tour/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/virtual-tour/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/indigo-layout/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/indigo-layout/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/filter-wrapper/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/filter-wrapper/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/chart-builder/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/chart-builder/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/form-builder/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/form-builder/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
cdn.pkgkit.com/undefined/awes-io/system-notify/undefined/css/main.css?v=20190617180425:1 Failed to load resource: the server responded with a status of 404 ()
cdn.pkgkit.com/undefined/awes-io/indigo-layout/undefined/css/main.css?v=20190617180425:1 Failed to load resource: the server responded with a status of 404 ()
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/modal-window/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/modal-window/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/table-builder/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/table-builder/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/context-menu/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.pkgkit.com/undefined/awes-io/context-menu/undefined/js/main.js?v=20190617180425:1 Failed to load resource: net::ERR_FAILED
register:1 Access to script at 'https://cdn.pkgkit.com/undefined/awes-io/system-notify/undefined/js/main.js?v=20190617180425' from origin 'http://memberstudio.devel' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by yevhenlisovenko** [comment]
Hi @ThistleApps ,
thanks for the message.

1. First `undefined` in the URL (http://awescode.com/screenshots/Screenshot_18_06_19__08_38_22B8BE71.png)
we assume that there is no API key in `.env` file. 
```
PKGKIT_CDN_KEY={your_api_key_from_pkgkit_com}
```
If it does not exist or empty, please copy the demo key from [.env.example](https://github.com/awes-io/demo/blob/master/.env.example) (limited by time), or create your own (it's free) on [Package Kit](https://www.pkgkit.com), or load assets from localhost.

2. About `CORS policy: No 'Access-Control-Allow-Origin'`: You can use `https://localhost` or you have to create a project in [Package Kit](https://www.pkgkit.com), then change your API keys (in `composer.json` and in `.env`) as well you have to add your custom domain (memberstudio.devel) to your project in Package Kit to the allowed list of domain names. 

3. second `undefined` in the URL, we think it's because XAMPP doesn't support `exec`. We created a ticket for the issue: https://github.com/awes-io/awes-io/issues/70. Please follow the issue. Or if you don't want to wait you can use docker installation right now.
