### ISSUE TITLE
disallowed MIME type and CORS

### ISSUE THREAD

**Issue by anditsung** [awes-io/demo#3]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

Hello, i have this issue after installing the demo on my development server

Loading module from “https://s0.pkgkit.com/undefined/awes-io/chart-builder/v1.1.0/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/chart-builder/v1.1.0/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/chart-builder/v1.1.0/js/main.js?v=20190814075413”. login:42:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/context-menu/v1.1.2/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/context-menu/v1.1.2/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/context-menu/v1.1.2/js/main.js?v=20190814075413”. login:43:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/filter-wrapper/v1.1.0/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/filter-wrapper/v1.1.0/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/filter-wrapper/v1.1.0/js/main.js?v=20190814075413”. login:44:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/form-builder/v1.7.0/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/form-builder/v1.7.0/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/form-builder/v1.7.0/js/main.js?v=20190814075413”. login:45:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/indigo-layout/v1.10.15/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/indigo-layout/v1.10.15/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/indigo-layout/v1.10.15/js/main.js?v=20190814075413”. login:46:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/modal-window/v1.1.3/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/modal-window/v1.1.3/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/modal-window/v1.1.3/js/main.js?v=20190814075413”. login:47:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/system-notify/v1.2.3/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/system-notify/v1.2.3/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/system-notify/v1.2.3/js/main.js?v=20190814075413”. login:48:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/table-builder/v1.3.0/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/table-builder/v1.3.0/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/table-builder/v1.3.0/js/main.js?v=20190814075413”. login:49:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/theme-switcher/v1.1.0/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/theme-switcher/v1.1.0/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/theme-switcher/v1.1.0/js/main.js?v=20190814075413”. login:50:1
Loading module from “https://s0.pkgkit.com/undefined/awes-io/virtual-tour/v1.2.0/js/main.js?v=20190814075413” was blocked because of a disallowed MIME type (“text/html”). login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s0.pkgkit.com/undefined/awes-io/virtual-tour/v1.2.0/js/main.js?v=20190814075413. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
Module source URI is not allowed in this document: “https://s0.pkgkit.com/undefined/awes-io/virtual-tour/v1.2.0/js/main.js?v=20190814075413”. login:51:1
The script from “https://s0.pkgkit.com/undefined/awes-io/base-js/v1.8.3/js/main.js?v=20190814075413” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. login
Loading failed for the <script> with source “https://s0.pkgkit.com/undefined/awes-io/base-js/v1.8.3/js/main.js?v=20190814075413”. login:55:1

my server is
ubuntu 18.04
PHP 7.2.19-0ubuntu0.18.04.2
mysql  Ver 14.14 Distrib 5.7.27

i have add PKGKIT_CDN_KEY to .env and API to composer.json
i have add allowed domains too

![Screen Shot 2019-08-14 at 16 07 18](https://user-images.githubusercontent.com/1090413/63008876-a77b3500-bead-11e9-85bf-b45550d7903f.png)

i read [https://github.com/awes-io/demo/issues/1](url)
you can add the asset localy. how to do that?

**Comment by yevhenlisovenko** [comment]
Dear @anditsung,
please follow the link to fix your issue: https://github.com/awes-io/awes-io/issues/118
Best,
Yevhen
